/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface McpContent {
  contentType: string
  text?: string
  data?: string
  mimeType?: string
  uri?: string
}
export interface McpToolResult {
  content: Array<McpContent>
  isError?: boolean
}
export interface McpResourceContent {
  uri: string
  mimeType?: string
  text?: string
  blob?: string
}
export interface McpResourceResult {
  contents: Array<McpResourceContent>
}
export interface McpPromptMessage {
  role: string
  content: McpContent
}
export interface McpPromptResult {
  description?: string
  messages: Array<McpPromptMessage>
}
export interface ToolSchema {
  name: string
  description?: string
  inputSchema: string
}
export interface ResourceSchema {
  uri: string
  name: string
  description?: string
  mimeType?: string
}
export interface PromptSchema {
  name: string
  description?: string
  arguments?: string
}
export interface ServerOptions {
  name: string
  version: string
  description?: string
  logLevel?: string
}
export interface ListenOptions {
  transport: string
  port?: number
  host?: string
  path?: string
}
export interface JsonRpcRequest {
  jsonrpc: string
  id?: string
  method: string
  params?: string
}
export interface JsonRpcResponse {
  jsonrpc: string
  id?: string
  result?: string
  error?: string
}
export interface PluginOptions {
  name: string
  version?: string
}
export interface HookContext {
  requestId: string
  method: string
  timestamp: number
}
/** Create a text content block */
export declare function textContent(text: string): McpContent
/** Create an image content block */
export declare function imageContent(data: string, mimeType: string): McpContent
/** Create a resource reference content block */
export declare function resourceContent(uri: string, mimeType?: string | undefined | null): McpContent
/** Validate JSON Schema (returns error message or null) */
export declare function validateSchema(schemaJson: string, dataJson: string): string | null
/** Parse a JSON-RPC request from raw string */
export declare function parseJsonrpc(raw: string): JsonRpcRequest
/** Serialize a JSON-RPC success response */
export declare function jsonrpcOk(id: string | undefined | null, resultJson: string): string
/** Serialize a JSON-RPC error response */
export declare function jsonrpcError(id: string | undefined | null, code: number, message: string): string
export declare class McpServer {
  /** Create a new MCP server: */
  constructor(options: ServerOptions)
  /** Register a tool: */
  tool(name: string, schema: ToolSchema, handler: (err: Error | null, arg: string) => any): this
  /** Register a resource: */
  resource(name: string, uriPattern: string, schema: ResourceSchema, handler: (err: Error | null, arg: string) => any): this
  /** Register a prompt template */
  prompt(name: string, schema: PromptSchema, handler: (err: Error | null, arg: string) => any): this
  /** Register a plugin : */
  register(pluginName: string, options?: PluginOptions | undefined | null): this
  /** Add a pre-request lifecycle hook : */
  addHookPre(hook: (err: Error | null, arg: string) => any): this
  /** Add a post-response lifecycle hook */
  addHookPost(hook: (err: Error | null, arg: string) => any): this
  /** Add an error lifecycle hook : */
  addHookError(hook: (err: Error | null, arg: string) => any): this
  /** Decorate the server with custom values: */
  decorate(key: string, value: string): this
  /** Get a decorator value */
  getDecorator(key: string): string | null
  /** Handle an incoming JSON-RPC request (the core dispatch loop) */
  handleRequest(rawRequest: string): Promise<string>
  /** List all registered tools */
  listTools(): Array<string>
  /** List all registered resources */
  listResources(): Array<string>
  /** List all registered prompts */
  listPrompts(): Array<string>
  /** Get server info */
  serverInfo(): string
  /** Generate a unique request ID (for internal use) */
  generateId(): string
}
