/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface McpContent {
  contentType: string
  text?: string
  data?: string
  mimeType?: string
  uri?: string
}
export interface McpToolResult {
  content: Array<McpContent>
  isError?: boolean
}
export interface McpResourceContent {
  uri: string
  mimeType?: string
  text?: string
  blob?: string
}
export interface McpResourceResult {
  contents: Array<McpResourceContent>
}
export interface McpPromptMessage {
  role: string
  content: McpContent
}
export interface McpPromptResult {
  description?: string
  messages: Array<McpPromptMessage>
}
export interface ToolSchema {
  name: string
  description?: string
  inputSchema: string
}
export interface ResourceSchema {
  uri: string
  name: string
  description?: string
  mimeType?: string
}
export interface PromptSchema {
  name: string
  description?: string
  arguments?: string
}
export interface ServerOptions {
  name: string
  version: string
  description?: string
  logLevel?: string
}
export interface ListenOptions {
  transport: string
  port?: number
  host?: string
  path?: string
}
export interface JsonRpcRequest {
  jsonrpc: string
  id?: string
  method: string
  params?: string
}
export interface JsonRpcResponse {
  jsonrpc: string
  id?: string
  result?: string
  error?: string
}
export interface PluginOptions {
  name: string
  version?: string
}
export interface HookContext {
  requestId: string
  method: string
  timestamp: number
}
export interface PluginDefinition {
  name: string
  factory: (server: McpServer, opts?: Record<string, unknown>) => void | Promise<void>
  meta?: Record<string, unknown>
}
/** Create a text content block */
export declare function textContent(text: string): McpContent
/** Create an image content block */
export declare function imageContent(data: string, mimeType: string): McpContent
/** Create a resource reference content block */
export declare function resourceContent(uri: string, mimeType?: string | undefined | null): McpContent
/** Validate JSON Schema (returns error message or null) */
export declare function validateSchema(schemaJson: string, dataJson: string): string | null
/** Parse a JSON-RPC request from raw string */
export declare function parseJsonrpc(raw: string): JsonRpcRequest
/** Serialize a JSON-RPC success response */
export declare function jsonrpcOk(id: string | undefined | null, resultJson: string): string
/** Serialize a JSON-RPC error response */
export declare function jsonrpcError(id: string | undefined | null, code: number, message: string): string
export declare function definePlugin(name: string, factory: PluginDefinition['factory'], meta?: Record<string, unknown>): PluginDefinition
export declare class McpServer {
  /** Create a new MCP server: */
  constructor(options: ServerOptions)
  readonly log: {
    error: (...args: unknown[]) => void
    warn: (...args: unknown[]) => void
    info: (...args: unknown[]) => void
    debug: (...args: unknown[]) => void
  }
  /** Register a tool */
  tool(name: string, schema: Partial<Omit<ToolSchema, 'name'>> | ((args: Record<string, unknown>) => unknown | Promise<unknown>), handler?: (args: Record<string, unknown>) => unknown | Promise<unknown>): this
  /** Register a resource */
  resource(name: string, uriPattern: string, schema: Partial<Omit<ResourceSchema, 'name' | 'uri'>> | ((uri: string) => unknown | Promise<unknown>), handler?: (uri: string) => unknown | Promise<unknown>): this
  /** Register a prompt */
  prompt(name: string, schema: Partial<Omit<PromptSchema, 'name'>> | ((args: Record<string, unknown>) => unknown | Promise<unknown>), handler?: (args: Record<string, unknown>) => unknown | Promise<unknown>): this
  /** Register a plugin */
  register(plugin: string | ((server: McpServer, opts?: Record<string, unknown>) => void | Promise<void>) | PluginDefinition, options?: Record<string, unknown>): Promise<this>
  /** Add a lifecycle hook */
  addHook(event: 'pre' | 'preRequest' | 'post' | 'postResponse' | 'error' | 'onError', hook: (err: Error | null, arg: string) => any): this
  /** Decorate the server with custom values */
  decorate(key: string, value: unknown): this
  /** Get a decorator value */
  getDecorator(key: string): unknown
  /** Start the server transport */
  listen(options?: ListenOptions): Promise<this>
  /** Handle an incoming JSON-RPC request */
  handleRequest(rawRequest: string): Promise<string>
  /** List all registered tools */
  listTools(): Array<string>
  /** List all registered resources */
  listResources(): Array<string>
  /** List all registered prompts */
  listPrompts(): Array<string>
  /** Parse server info */
  info(): {
    name: string
    version: string
    description?: string
    mcpifyVersion?: string
    tools: Array<string>
    resources: Array<string>
    prompts: Array<string>
  }
  /** Get raw server info JSON */
  serverInfo(): string
  /** Generate a unique request ID (for internal use) */
  generateId(): string
}
