/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'mcpify.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./mcpify.android-arm64.node')
          } else {
            nativeBinding = require('mcpify-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'mcpify.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./mcpify.android-arm-eabi.node')
          } else {
            nativeBinding = require('mcpify-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'mcpify.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mcpify.win32-x64-msvc.node')
          } else {
            nativeBinding = require('mcpify-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'mcpify.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mcpify.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('mcpify-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'mcpify.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mcpify.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('mcpify-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'mcpify.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./mcpify.darwin-universal.node')
      } else {
        nativeBinding = require('mcpify-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'mcpify.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./mcpify.darwin-x64.node')
          } else {
            nativeBinding = require('mcpify-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'mcpify.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mcpify.darwin-arm64.node')
          } else {
            nativeBinding = require('mcpify-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'mcpify.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./mcpify.freebsd-x64.node')
      } else {
        nativeBinding = require('mcpify-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mcpify.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mcpify.linux-x64-musl.node')
            } else {
              nativeBinding = require('mcpify-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mcpify.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mcpify.linux-x64-gnu.node')
            } else {
              nativeBinding = require('mcpify-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mcpify.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mcpify.linux-arm64-musl.node')
            } else {
              nativeBinding = require('mcpify-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mcpify.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mcpify.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('mcpify-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mcpify.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mcpify.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('mcpify-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mcpify.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mcpify.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('mcpify-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mcpify.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mcpify.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('mcpify-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mcpify.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mcpify.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('mcpify-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'mcpify.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mcpify.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('mcpify-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const {
  McpServer: NativeMcpServer,
  textContent,
  imageContent,
  resourceContent,
  validateSchema,
  parseJsonrpc,
  jsonrpcOk,
  jsonrpcError,
} = nativeBinding

function normalizeToolSchema(name, schema = {}) {
  const inputSchema = schema.inputSchema ?? schema.input_schema ?? { type: 'object' }
  return {
    name,
    description: schema.description,
    inputSchema: typeof inputSchema === 'string' ? inputSchema : JSON.stringify(inputSchema),
  }
}

function normalizeResourceSchema(name, uriPattern, schema = {}) {
  return {
    uri: schema.uri ?? uriPattern,
    name,
    description: schema.description,
    mimeType: schema.mimeType ?? schema.mime_type,
  }
}

function normalizePromptSchema(name, schema = {}) {
  const args = schema.arguments ?? []
  return {
    name,
    description: schema.description,
    arguments: typeof args === 'string' ? args : JSON.stringify(args),
  }
}

function decodeNativeArg(first, second) {
  if (typeof second !== 'undefined') return second
  return first
}

class McpServer {
  #native
  #decorators = new Map()
  #stdioState = null
  #httpState = null

  constructor(options) {
    this.#native = new NativeMcpServer(options)
  }

  get log() {
    return {
      error: (...args) => console.error(...args),
      warn: (...args) => console.warn(...args),
      info: (...args) => console.info(...args),
      debug: (...args) => console.debug(...args),
    }
  }

  tool(name, schema, handler) {
    if (typeof schema === 'function') {
      handler = schema
      schema = {}
    }
    if (typeof handler !== 'function') {
      throw new TypeError('tool() requires a handler function')
    }

    this.#native.tool(
      name,
      normalizeToolSchema(name, schema),
      async (err, rawArgs) => {
        if (err) throw err
        const argsJson = decodeNativeArg(err, rawArgs)
        const parsedArgs = argsJson ? JSON.parse(argsJson) : {}
        const result = await handler(parsedArgs)
        return JSON.stringify(result)
      },
    )

    return this
  }

  resource(name, uriPattern, schema, handler) {
    if (typeof schema === 'function') {
      handler = schema
      schema = {}
    }
    if (typeof handler !== 'function') {
      throw new TypeError('resource() requires a handler function')
    }

    this.#native.resource(
      name,
      uriPattern,
      normalizeResourceSchema(name, uriPattern, schema),
      async (err, rawUri) => {
        if (err) throw err
        const uri = decodeNativeArg(err, rawUri)
        const result = await handler(uri)
        return JSON.stringify(result)
      },
    )

    return this
  }

  prompt(name, schema, handler) {
    if (typeof schema === 'function') {
      handler = schema
      schema = {}
    }
    if (typeof handler !== 'function') {
      throw new TypeError('prompt() requires a handler function')
    }

    this.#native.prompt(
      name,
      normalizePromptSchema(name, schema),
      async (err, rawArgs) => {
        if (err) throw err
        const argsJson = decodeNativeArg(err, rawArgs)
        const parsedArgs = argsJson ? JSON.parse(argsJson) : {}
        const result = await handler(parsedArgs)
        return JSON.stringify(result)
      },
    )

    return this
  }

  async register(plugin, opts = {}) {
    if (typeof plugin === 'function') {
      await plugin(this, opts)
      return this
    }
    if (plugin && typeof plugin.factory === 'function') {
      await plugin.factory(this, opts)
      return this
    }

    this.#native.register(plugin, opts)
    return this
  }

  addHook(event, hook) {
    switch (event) {
      case 'pre':
      case 'preRequest':
        this.#native.addHookPre(hook)
        break
      case 'post':
      case 'postResponse':
        this.#native.addHookPost(hook)
        break
      case 'error':
      case 'onError':
        this.#native.addHookError(hook)
        break
      default:
        throw new Error(`Unknown hook event: ${event}`)
    }

    return this
  }

  async listen(options = {}) {
    const transport = options.transport ?? 'stdio'

    if (transport === 'stdio') {
      if (this.#stdioState) {
        return this
      }

      let buffer = ''
      const onData = async (chunk) => {
        buffer += chunk.toString()
        const lines = buffer.split(/\r?\n/)
        buffer = lines.pop() ?? ''

        for (const line of lines) {
          const message = line.trim()
          if (!message) {
            continue
          }

          try {
            const response = await this.handleRequest(message)
            if (response) {
              process.stdout.write(`${response}\n`)
            }
          } catch (err) {
            const errorMessage = err instanceof Error ? err.message : String(err)
            process.stdout.write(`${jsonrpcError(null, -32603, errorMessage)}\n`)
          }
        }
      }

      process.stdin.setEncoding('utf8')
      process.stdin.on('data', onData)
      process.stdin.resume()

      this.#stdioState = { onData }
      return this
    }

    if (transport === 'http') {
      if (this.#httpState) {
        return this
      }

      const http = require('http')
      const host = options.host ?? '127.0.0.1'
      const port = options.port ?? 3000
      const endpoint = options.path ?? '/mcp'

      const server = http.createServer(async (req, res) => {
        const requestUrl = req.url ?? '/'

        if (req.method === 'GET' && requestUrl === '/health') {
          res.writeHead(200, { 'Content-Type': 'application/json' })
          res.end(JSON.stringify({ status: 'ok' }))
          return
        }

        if (req.method !== 'POST' || requestUrl !== endpoint) {
          res.writeHead(404, { 'Content-Type': 'application/json' })
          res.end(JSON.stringify({ error: 'Not found' }))
          return
        }

        let body = ''
        req.setEncoding('utf8')
        req.on('data', (chunk) => {
          body += chunk
        })

        req.on('end', async () => {
          try {
            const response = await this.handleRequest(body)
            res.writeHead(200, { 'Content-Type': 'application/json' })
            res.end(response)
          } catch (err) {
            const errorMessage = err instanceof Error ? err.message : String(err)
            res.writeHead(500, { 'Content-Type': 'application/json' })
            res.end(jsonrpcError(null, -32603, errorMessage))
          }
        })
      })

      await new Promise((resolve, reject) => {
        server.once('error', reject)
        server.listen(port, host, () => {
          server.off('error', reject)
          resolve()
        })
      })

      this.#httpState = { server, host, port, endpoint }
      return this
    }

    throw new Error(`Unsupported transport: ${transport}`)
  }

  decorate(key, value) {
    if (key in this) {
      throw new Error(`Cannot overwrite existing property: ${key}`)
    }

    this.#decorators.set(key, value)
    Object.defineProperty(this, key, {
      configurable: false,
      enumerable: true,
      get: () => this.#decorators.get(key),
    })

    if (typeof value === 'string') {
      this.#native.decorate(key, value)
    }

    return this
  }

  getDecorator(key) {
    if (this.#decorators.has(key)) {
      return this.#decorators.get(key)
    }
    return this.#native.getDecorator(key)
  }

  handleRequest(rawRequest) {
    return this.#native.handleRequest(rawRequest)
  }

  listTools() {
    return this.#native.listTools()
  }

  listResources() {
    return this.#native.listResources()
  }

  listPrompts() {
    return this.#native.listPrompts()
  }

  info() {
    return JSON.parse(this.#native.serverInfo())
  }

  serverInfo() {
    return this.#native.serverInfo()
  }

  generateId() {
    return this.#native.generateId()
  }
}

function definePlugin(name, factory, meta = {}) {
  return { name, factory, meta }
}

module.exports.McpServer = McpServer
module.exports.definePlugin = definePlugin
module.exports.textContent = textContent
module.exports.imageContent = imageContent
module.exports.resourceContent = resourceContent
module.exports.validateSchema = validateSchema
module.exports.parseJsonrpc = parseJsonrpc
module.exports.jsonrpcOk = jsonrpcOk
module.exports.jsonrpcError = jsonrpcError
